// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeigutwkofelmokspdsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlaWd1dHdrb2ZlbG1va3NwZHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDU3MjQsImV4cCI6MjA2MTE4MTcyNH0.5US53n1L0ek4gsLoqkPzQnkt0A2X3LxW5quY35u-hsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);